---
apiVersion: v1
kind: Pod
metadata:
  name: caddy
  labels:
    name: static-site
  namespace: static-site
spec:
  containers:
    - name: caddy
      image: chlokesh1306/lokesh:latest
      env:
        - name: CADDY_PORT
          valueFrom:
            configMapKeyRef:
              name: ports
              key: caddy_port
      startupProbe:
        exec:
          command:
            - /bin/sh
            - -c
            - wget -qO- http://localhost:$CADDY_PORT/index.html > /dev/null
        failureThreshold: 3
        periodSeconds: 5
      livenessProbe:
        exec:
          command:
            - /bin/sh
            - -c
            - wget -qO- http://localhost:$CADDY_PORT/index.html > /dev/null
        initialDelaySeconds: 3
        periodSeconds: 3
      readinessProbe:
        exec:
          command:
            - /bin/sh
            - -c
            - wget -qO- http://localhost:$CADDY_PORT/index.html > /dev/null
        initialDelaySeconds: 3
        periodSeconds: 3
  imagePullSecrets:
    - name: docker
