---
apiVersion: v1
data:
  .dockerconfigjson: |
                       eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tl
                       ci5pby92MS8iOnsidXNlcm5hbWUiOiJjaGxva2Vz
                       aDEzMDYiLCJwYXNzd29yZCI6IlN1c2htaXRhY2g3
                       MCIsImVtYWlsIjoiY2hhbGxhZ3VsbGEubEBub3J0
                       aGVhc3Rlcm4uZWR1IiwiYXV0aCI6IlkyaHNiMnRs
                       YzJneE16QTJPbE4xYzJodGFYUmhZMmczTUE9PSJ9fX0=
kind: Secret
metadata:
    name: docker
    namespace: static-site
type: kubernetes.io/dockerconfigjson
