---
apiVersion: v1
kind: Service
metadata:
  name: static-site-service
  namespace: static-site
spec:
  type: NodePort
  selector:
    name: static-site
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000
